name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run unit tests
        run: |
          python3 tests/test_authorization.py

      - name: Build Docker image
        run: |
          docker build -t analyzer-app .

      - name: Run Docker image
        run: |
          docker run -d -p 5001:5000 analyzer-app
